# Generated by Django 6.0 on 2026-02-10 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, choices=[('chatbot', 'Chatbot'), ('contact_form', 'Contact Form')], max_length=20, null=True)),
                ('intent', models.CharField(choices=[('pricing', 'Pricing'), ('interest', 'Interest'), ('contact', 'Contact'), ('general', 'General')], default='general', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='domains.website')),
            ],
            options={
                'unique_together': {('website', 'email')},
            },
        ),
    ]
