# Generated by Django 6.0 on 2026-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
